export const SET_LOGIN = 'SET_LOGIN';
export const SHOW_MODAL_THONGTINCANHAN = 'user/SHOW_MODAL_THONGTINCANHAN';
export const HIRE_MODAL_THONGTINCANHAN = 'user/HIRE_MODAL_THONGTINCANHAN';

/* dịch vụ action */
export const SHOW_MODAL_LOAIDICHVU = 'SHOW_MODAL_LOAIDICHVU';
export const HIRE_MODAL_LOAIDICHVU = 'HIRE_MODAL_LOAIDICHVU';
export const FETCH_LOAIDICHVU = 'FETCH_LOAIDICHVU';
export const ADD_LOAIDICHVU = 'ADD_LOAIDICHVU';
export const DELETE_LOAIDICHVU = 'DELETE_LOAIDICHVU';
export const UPDATE_LOAIDICHVU = 'UPDATE_LOAIDICHVU';
export const DROPDOWN_TABLE_DICHVU = 'DROPDOWN_TABLE_DICHVU';

export const FETCH_DICHVU = 'FETCH_DICHVU';
export const SHOW_MODAL_DICHVU = 'SHOW_MODAL_DICHVU';
export const HIRE_MODAL_DICHVU = 'HIRE_MODAL_DICHVU';
export const ADD_DICHVU = 'ADD_DICHVU';
export const DELETE_DICHVU = 'DELETE_DICHVU';
export const UPDATE_DICHVU = 'UPDATE_DICHVU';
/// quy trinh dich vu 
export const SET_DATA_QUYTRINHDICHVUBYID = 'SET_DATA_QUYTRINHDICHVUBYID';


export const CHECK_DATA = 'CHECK_DATA';

/* Điều dưỡng action */
export const SHOW_MODAL_DIEUDUONG = 'dieuduong/SHOW_MODAL_DIEUDUONG';
export const SHOW_MODAL_VITIEN = 'dieuduong/SHOW_MODAL_VITIEN';
export const SHOW_MODAL_GIAYPHEPHANHNGHE = 'dieuduong/SHOW_MODAL_GIAYPHEPHANHNGHE';
export const HIRE_MODAL_DIEUDUONG = 'dieuduong/HIRE_MODAL_DIEUDUONG';
export const HIRE_MODAL_VITIEN = 'dieuduong/HIRE_MODAL_VITIEN';
export const HIRE_MODAL_GIAYPHEPHANHNGHE = 'dieuduong/HIRE_MODAL_GIAYPHEPHANHNGHE';
export const SET_DATA_LISTDIEUDUONG = 'dieuduong/SET_DATA_LISTDIEUDUONG';
export const ADD_DIEUDUONG = 'dieuduong/ADD_DIEUDUONG';
export const UPDATE_DIEUDUONG = 'dieuduong/UPDATE_DIEUDUONG';
export const SET_DIEUDUONG_BY_DAOTAOVIEN = 'dieuduong/SET_DIEUDUONG_BY_DAOTAOVIEN';


/* Tỉnh thành action*/
export const SET_DATA_TINHTHANH = 'tinhthanh/SET_DATA_TINHTHANH';