export const SET_LOGIN = 'SET_LOGIN';
export const SHOW_MODAL_LOAIDICHVU = 'SHOW_MODAL_LOAIDICHVU';
export const SHOW_MODAL_DICHVU = 'SHOW_MODAL_DICHVU';
export const FETCH_LOAIDICHVU = 'FETCH_LOAIDICHVU';
export const FETCH_DICHVU = 'FETCH_DICHVU';
export const ADD_LOAIDICHVU = 'ADD_LOAIDICHVU';