package com.isc.dto;

import java.sql.Date;

import lombok.Data;

@Data
public class AddManagerDto {
	
	private String ADMIN_HOTEN;
	
	private String ADMIN_EMAIL;
	
	private String ADMIN_GIOITINH;
	
	private String ADMIN_USERNAME;
	
	private String ADMIN_PASSWORD;
	
	private String ADMIN_DIACHI;
	
	private String ADMIN_CMND;
	
	private Date ADMIN_CMNDNGAYCAP;

	private String ADMIN_CMNDNOICAP;
	
	private String ADMIN_CMNDMATTRUOC;
	
	private String ADMIN_CMNDMATSAU;
	
	private String ADMIN_AVATAR;
	
	private int ADMIN_TINHTRANG;
	
	private String ADMIN_SDT;
	
	private int ADMIN_CHUCVU;
	
	private String ADMIN_NGAYSINH;

	
	public AddManagerDto( String aDMIN_HOTEN, String aDMIN_EMAIL, String aDMIN_GIOITINH,
			String aDMIN_USERNAME, String aDMIN_PASSWORD, String aDMIN_DIACHI, String aDMIN_CMND,
			Date aDMIN_CMNDNGAYCAP, String aDMIN_CMNDNOICAP, String aDMIN_CMNDMATTRUOC, String aDMIN_CMNDMATSAU,
			String aDMIN_AVATAR, int aDMIN_TINHTRANG, String aDMIN_SDT, int aDMIN_CHUCVU, String aDMIN_NGAYSINH) {
		super();
	
		ADMIN_HOTEN = aDMIN_HOTEN;
		ADMIN_EMAIL = aDMIN_EMAIL;
		ADMIN_GIOITINH = aDMIN_GIOITINH;
		ADMIN_USERNAME = aDMIN_USERNAME;
		ADMIN_PASSWORD = aDMIN_PASSWORD;
		ADMIN_DIACHI = aDMIN_DIACHI;
		ADMIN_CMND = aDMIN_CMND;
		ADMIN_CMNDNGAYCAP = aDMIN_CMNDNGAYCAP;
		ADMIN_CMNDNOICAP = aDMIN_CMNDNOICAP;
		ADMIN_CMNDMATTRUOC = aDMIN_CMNDMATTRUOC;
		ADMIN_CMNDMATSAU = aDMIN_CMNDMATSAU;
		ADMIN_AVATAR = aDMIN_AVATAR;
		ADMIN_TINHTRANG = aDMIN_TINHTRANG;
		ADMIN_SDT = aDMIN_SDT;
		ADMIN_CHUCVU = aDMIN_CHUCVU;
		ADMIN_NGAYSINH = aDMIN_NGAYSINH;
	}


	
	
}
