export const FETCH_SERVICETYPE = 'serviceType/FETCH_SERVICETYPE';
export const FETCH_SERVICE = 'service/FETCH_SERVICE';
export const SHOW_COMPONENT_SERVICE = 'service/SHOW_COMPONENT_SERVICE';
export const HIRE_COMPONENT_SERVICE = 'service/HIRE_COMPONENT_SERVICE ';
export const FETCH_TINHTHANH = 'tinhthanh/FETCH_TINHTHANH';